### ISSUE TITLE
seam 0.1.29 更新

### ISSUE THREAD

**Issue by Borber** [chen310/SeamPotPlayer#3]
抱歉哈 seam 0.1.29 更新后 调用方式改为了 `.\seam.exe -l live -i rid` 您这边需要稍微修改一下调用, 

以及我这边把您的项目放到 seam 的 README, 相关项目中了

**Comment by chen310** [comment]
好的，已修改👍

**Comment by justdoiting** [comment]
seam 0.1.32之后的版本不知道改了什么，已经不能作为插件使用

**Comment by Borber** [comment]
> seam 0.1.32之后的版本不知道改了什么，已经不能作为插件使用

请问你解析的什么平台， 我看看是不是 seam的问题

**Comment by justdoiting** [comment]
> > seam 0.1.32之后的版本不知道改了什么，已经不能作为插件使用
> 
> 请问你解析的什么平台， 我看看是不是 seam的问题

斗鱼，B站，panda都试了，一个都不行，退回0.1.32就正常

**Comment by Borber** [comment]
> > > seam 0.1.32之后的版本不知道改了什么，已经不能作为插件使用
> > 
> > 
> > 请问你解析的什么平台， 我看看是不是 seam的问题
> 
> 斗鱼，B站，panda都试了，一个都不行，退回0.1.32就正常

我知道了， 应该是 0.1.33 修改了默认显示（因为现在新增了 封面图，主播名这种，）， -a 显示全部信息， 不加-a就只显示链接了， @chen310  需要稍微修改一下脚本

![image](https://github.com/chen310/SeamPotPlayer/assets/30563826/4dcebb7c-692c-4698-99e6-80fc605496b8)

**Comment by chen310** [comment]
@Borber @justdoiting 好的，我有空修改一下

**Comment by Borber** [comment]
@chen310  @justdoiting  真的很抱歉有这种破坏性更新， 但目前增加的解析字段确实会导致仅需要播放源的用户看到很多不必要的信息，后续如果有迫不得已的破坏性更新我一定第一时间反馈

**Comment by chen310** [comment]
@justdoiting 已适配，更新插件试试

**Comment by justdoiting** [comment]
> @justdoiting 已适配，更新插件试试

已测试，可用

**Comment by justdoiting** [comment]
还有一个问题，抖音还可以通过https://live.douyin.com/XXX来打开直播间，XXX为用户ID，测试seam是可以解析的，但是插件没有解析出来
![image](https://github.com/chen310/SeamPotPlayer/assets/109136320/2b5064c2-97c2-42b5-9dd7-9160da95618d)

**Comment by chen310** [comment]
@justdoiting 更新了，你试试

**Comment by justdoiting** [comment]
> @justdoiting 更新了，你试试

![image](https://github.com/chen310/SeamPotPlayer/assets/109136320/a63eac84-faf9-4891-a181-45f35c654cb4)
可以用
