### ISSUE TITLE
下载后打开potplayer报错

### ISSUE THREAD

**Issue by ggrreeeedd** [chen310/SeamPotPlayer#4]
--------PotPlayer's AngelScript console--------
MediaPlayParse - seam.as (7, 1) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (33, 251) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (404, 114) : ERR  : Unexpected token '<integer constant>'
MediaPlayParse - seam.as (438, 73) : ERR  : Unexpected token '/'
MediaPlayParse - seam.as (1591, 25) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (1720, 102) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1720, 108) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (1720, 169) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1720, 175) : ERR  : Unexpected token '/'
MediaPlayParse - seam.as (1720, 182) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1720, 188) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (1729, 73) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1729, 79) : ERR  : Unexpected token '/'
MediaPlayParse - seam.as (1729, 86) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1729, 92) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (1738, 79) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1738, 85) : ERR  : Unexpected token '/'
MediaPlayParse - seam.as (1738, 92) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1738, 98) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (1882, 48) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (7, 1) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (33, 251) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (404, 114) : ERR  : Unexpected token '<integer constant>'
MediaPlayParse - seam.as (438, 73) : ERR  : Unexpected token '/'
MediaPlayParse - seam.as (1591, 25) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (1720, 102) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1720, 108) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (1720, 169) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1720, 175) : ERR  : Unexpected token '/'
MediaPlayParse - seam.as (1720, 182) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1720, 188) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (1729, 73) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1729, 79) : ERR  : Unexpected token '/'
MediaPlayParse - seam.as (1729, 86) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1729, 92) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (1738, 79) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1738, 85) : ERR  : Unexpected token '/'
MediaPlayParse - seam.as (1738, 92) : ERR  : Unexpected token '&'
MediaPlayParse - seam.as (1738, 98) : ERR  : Unexpected token '<'
MediaPlayParse - seam.as (1882, 48) : ERR  : Unexpected token '<'
SubtitleSearch - OpenSubtitle.as (54, 1) : INFO : Compiling dictionary[] OldSubtitleSearch(string, dictionary)
SubtitleSearch - OpenSubtitle.as (98, 23) : WARN : Variable 'len' hides another variable of same name in outer scope
SubtitleSearch - podnapisi.as (202, 1) : INFO : Compiling dictionary[] SubtitleSearch(string, dictionary)
SubtitleSearch - podnapisi.as (260, 14) : WARN : Variable 'title' hides another variable of same name in outer scope
SubtitleSearch - podnapisi.as (269, 15) : WARN : Variable 'year' hides another variable of same name in outer scope
SubtitleSearch - titlovi.as (112, 1) : INFO : Compiling dictionary[] SubtitleSearch(string, dictionary)
SubtitleSearch - titlovi.as (148, 13) : WARN : Variable 'title' hides another variable of same name in outer scope
SubtitleSearch - titlovi.as (176, 14) : WARN : Variable 'year' hides another variable of same name in outer scope
SubtitleSearch - ysubs.as (110, 1) : INFO : Compiling dictionary[] SubtitleSearch(string, dictionary)
SubtitleSearch - ysubs.as (163, 28) : WARN : Variable 'len' hides another variable of same name in outer scope
SubtitleTranslate - bing.as (193, 1) : INFO : Compiling string Translate(string, string&in, string&in)
SubtitleTranslate - bing.as (227, 17) : WARN : Variable 'i' hides another variable of same name in outer scope
SubtitleTranslate - bing.as (227, 24) : WARN : Variable 'len' hides another variable of same name in outer scope
SubtitleTranslate - google.as (21, 1) : INFO : Compiling string JsonParseOld(string)
SubtitleTranslate - google.as (35, 21) : WARN : Variable 'len' hides another variable of same name in outer scope

**Comment by chen310** [comment]
可能是 potplayer 版本过低，或者不小心修改到seam.as文件导致报错

**Comment by ggrreeeedd** [comment]
> 可能是potplayer版本过低，或者不小心修改到seam.as文件导致报错

MediaPlayParse - seam.as用的是昨天更新后的，potplayer64位版本230905，都是最新的
